### ISSUE TITLE
Bouncing Balls

### ISSUE THREAD

**Issue by Bhavesh76** [a-kozhanov/codewars-csharp#90]
https://www.codewars.com/kata/5544c7a5cb454edb3c000047/csharp

code is not working it showing  error 401.

**Comment by a-kozhanov** [comment]
@Bhavesh76 
[6kyu/README.md 10 Bouncing Balls](https://github.com/a-kozhanov/codewars-csharp/blob/master/CodeWars/6kyu/README.md)
[BouncingBalls.cs](https://github.com/a-kozhanov/codewars-csharp/blob/master/CodeWars/6kyu/BouncingBalls.cs)

`404 “This is not the web page you are looking for”`

The file "Bouncing balls.cs" has not been committed it lies locally on my computer. I will make a git commit\push tomorrow.

My solution:

```
namespace CodeWars
{
    public class BouncingBalls
    {
        public static int bouncingBall(double h, double bounce, double window)
        {
            return h > 0 && bounce > 0 && bounce < 1 && window < h
                ? h < window ? -1 : 2 + bouncingBall(h * bounce, bounce, window)
                : -1;
        }
    }
}
```

**Comment by a-kozhanov** [comment]
@Bhavesh76 

Added solution "Bouncing Balls"
[BouncingBalls.cs](https://github.com/a-kozhanov/codewars-csharp/blob/master/CodeWars/6kyu/BouncingBalls.cs)
[BouncingBallsTests.cs](https://github.com/a-kozhanov/codewars-csharp/blob/master/CodeWarsTests/6kyu/BouncingBallsTests.cs)
